sonar.projectKey=viaja-junto
sonar.projectName=ViajaJunto

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,backend/test
sonar.test.inclusions=backend/src/**/*.spec.ts,backend/test/**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,backend/generated/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Faz o scanner aguardar o Quality Gate e falhar o job se ele reprovar
sonar.qualitygate.wait=true
